Task 1: Memory Layout & Summation Speed Comparison

In [1]:
import numpy as np
import sys,time

# create data
l=list(range(1000000))
a=np.array(l)

# memory
print("Python list memory:",sys.getsizeof(l)+sum(sys.getsizeof(i) for i in l),"bytes")
print("NumPy array memory:",a.nbytes,"bytes")

# time for list sum
t=time.time()
sum(l)
print("Time using Python list:",time.time()-t,"seconds")

# time for numpy sum
t=time.time()
a.sum()
print("Time using NumPy array:",time.time()-t,"seconds")

# NumPy uses contiguous memory and C loops, so it uses less memory and runs faster

Python list memory: 36000056 bytes
NumPy array memory: 8000000 bytes
Time using Python list: 0.003383636474609375 seconds
Time using NumPy array: 0.0006535053253173828 seconds


Task 2: Array Creation and Shaping

In [2]:
import numpy as np

# 1. Convert list to NumPy array
block_ids = [101,102,103,104,105,106,107,108,109,110,111,112]
city_array = np.array(block_ids)
print("City block array:", city_array)

# 2. Create 3x3 zero matrix and set diagonal to 255
z = np.zeros((3,3), dtype=int)
np.fill_diagonal(z,255)
print("3x3 Zero matrix with diagonal 255:\n", z)

# 3. Create range and reshape
a = np.arange(10,70,10).reshape(2,3)
print("Reshaped array from 10–50:\n", a)

# 4. Linspace values
b = np.linspace(0,1,7)
print("Linspace array (7 values 0 to 1):", b)

City block array: [101 102 103 104 105 106 107 108 109 110 111 112]
3x3 Zero matrix with diagonal 255:
 [[255   0   0]
 [  0 255   0]
 [  0   0 255]]
Reshaped array from 10–50:
 [[10 20 30]
 [40 50 60]]
Linspace array (7 values 0 to 1): [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


Task 3: Broadcasting Operations

In [3]:
import numpy as np

# base salary of 3 employees for 4 days
base_pay = np.array([[100,100,100,100],
                     [200,200,200,200],
                     [300,300,300,300]])

# bonus for each day
daily_bonus = np.array([10,20,30,40])

# broadcasting addition
total_pay = base_pay + daily_bonus

print("Total pay matrix after broadcasting addition:\n", total_pay)

# 1x4 daily_bonus is automatically expanded to 3x4,
# so it can be added to the 3x4 base_pay matrix.

Total pay matrix after broadcasting addition:
 [[110 120 130 140]
 [210 220 230 240]
 [310 320 330 340]]


Task 4: Vectorized Conditional Computation

In [4]:
import numpy as np

# original readings
readings = np.array([-2,-1,0,1,2])

# vectorized condition
result = np.where(readings >= 0, readings**2, readings**3)

print("Original readings:", readings)
print("Transformed results:", result)

Original readings: [-2 -1  0  1  2]
Transformed results: [-8 -1  0  1  4]
