NUMPY :-
NUMPY = NUMERICAL PYTHON

IT IS USED FOR:
FAST MATHEMATICAL OPERATIONS
WORKING WITH LARGE DATASETS
SCIENTIFIC COMPUTING

In [1]:
import numpy as np

PYTHON LIST  VS  NUMPY ARRAY

NUMBERS=[1,2,3,4]
DATA=[1,"hello",3.5]

-CAN STORE DIFFERRENT DATATYPES
-STORED IN SCATTERED MEMORY
-SLOWER FOR LARGER CALCULATIONS

NUMPY ARRAY:
arr=np.array([1,2,3,4])

-STORES SAME DATATYPE
-STORED IN CONTINUOUS MEMOFRY
-MUCH FASTER
-SUPPORTS MATHEMATICAL OPERATIONS

MEMORY DIFFERENCE: 
PYTHON LIST:-                                         NUMPY ARRAY:-
--------------------------                         ------------------------------- 
-FLEXIBLE                                             -FIXED DATA TYPE
-SLOWER                                               -FASTER
-DIFFERENT TYPES ALLOWED                              -SAME TYPE ONLY
-MEMORY SCATTERED                                     -MEMORY IS CONTINUOUS


In [ ]:
#ndarraay : N-dimensional array
arr=np.array([1,2,3,4]) #multiplies the list
print(arr * 2)

#normal list - repeats the lists
numbers=[1,5,3,2]
print(numbers * 2)

[2 4 6 8]
[1, 5, 3, 2, 1, 5, 3, 2]


In [ ]:
#CONVERTING LIST TO ARRAY
arr=np.array([10,20,30])
print(arr)

#2D example
arr1=np.array([[1,2,3],
             [4,5,6]])
print(arr1)

[10 20 30]
[[1 2 3]
 [4 5 6]]


In [ ]:
#np.zeros - creates array filled with zeros

arr=np.zeros(5)
print(arr)

#Array with 2 rows, 3 columns of zeros
arr1=np.zeros((2,3))
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#np.arange - similar to range function
np.arange(0,10,2)

#(start,stop,step)

array([0, 2, 4, 6, 8])

In [29]:
#np.linspace - creates evenely spaced numbers
print(np.linspace(0,10,5))   #0 to 10 only need 5 numbers 

#(start,stop,number of values)

#Logspace - evenly spaced log values
print(np.logspace(1,3,3))

[ 0.   2.5  5.   7.5 10. ]
[  10.  100. 1000.]


In [5]:
#np.ones()

arr=np.ones(5)
print(arr)

np.ones((2,3))
#2 rows, 3 columns

#Use when you need default values of 1

[1. 1. 1. 1. 1.]


array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#np.full - creates an array filled with any specific value and is useful for initialization.

print(np.full(5,7)) #One dimensional

print(np.full((2,4),8))
#(shape, fill value, [dtype]) - here dtype is optional

print(np.full((2,2),5,float))

print(np.full((3,3),True))

print(np.full((3,2),"NA")) #Used when making missing categorical values

[7 7 7 7 7]
[[8 8 8 8]
 [8 8 8 8]]
[[5. 5.]
 [5. 5.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[['NA' 'NA']
 ['NA' 'NA']
 ['NA' 'NA']]


In [14]:
#if all 5 students get a bonus marks of 2

marks=np.array([80,75,90,85,88])
bonus=np.full(marks.shape,2)

final_marks=marks+bonus
print(final_marks)

[82 77 92 87 90]


In [ ]:
#np.eye - creates identity matrix [diagonal=1]

print(np.eye(3))

print(np.diag([1,2,3])) #creates diagonal matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [20]:
#np.random - creates an array of random numbers between 0 and 1

print(np.random.rand(4))

print(np.random.rand(2,3))

print(np.random.randint(1,10,5)) #creates 5 random numbers between 1 and 9

[0.58045268 0.6544221  0.87481497 0.99151408]
[[0.38349429 0.90283024 0.29786802]
 [0.51011635 0.82870591 0.19921046]]
[8 8 2 5 7]


In [25]:
#random choice
colors=["red","blue","orange","green"]
print(np.random.choice(colors))

#Multiple selection
print(np.random.choice(colors,size=5))

green
['orange' 'green' 'blue' 'orange' 'green']


BROADCASTING - ALLOWS OPERATIONS BETWEEN ARRAYS OF DIFFERENT SHAPES

BROADCASTING RULES-
TWO ARRAYS ARE CAPABLE IF:

1. THEY HAVE SAME SHAPE
     OR

2. ONE OF THEM IS 1
    OR

3. SMALLER ARRAY CAN STRETCH TO MATCH LARGER

In [31]:
arr=np.array([1,2,3])

print(arr+5)

[6 7 8]


In [ ]:
#Broadcasting 1D with 2D

arr=np.array([[1,2,3],
              [4,5,6]])

b=np.array([10,20,30])

print(arr+b)

[[11 22 33]
 [14 25 36]]


In [ ]:
#Broadcasting fails because we need to give 3 numbers in a and 3 numbers in b or 2 in a and 2 in b not different numbers
a=np.array(([1,2,3],
            [4,5,6]))

b=np.array([1,2])

print(a+b)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [36]:
#Column broadcasting

arr=np.array([[1,2,3],
              [4,5,6]])

col=np.array([[10],
              [20]])

print(arr+col)

[[11 12 13]
 [24 25 26]]


VECTORIZATION - DOING OPERATIONS ON ENTIRE ARRAY AT ONCE INSTEAD OF USING LOOPS

VECTORIZATION MAKES IT:
-FASTER
-CLEANER CODE
-LESS MEMORY USAGE

In [38]:
#Square all numbers
arr=np.array([1,2,3,4])
print(arr**2)

[ 1  4  9 16]


In [40]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)

[5 7 9]


In [ ]:
#Conditional vectorization

arr=np.array([10,20,30,40])
print(arr>28) # (>) is a relational operator and gives true or false

[False False  True  True]


In [43]:
#Using condition to modify values

arr[arr>25]=100
print(arr)

[ 10  20 100 100]


In [45]:
#using where

np.where(arr>25,1,0)

array([0, 0, 1, 1])

In [47]:
#Mathematical operations

arr=np.array([1,2,3,4])

print(np.sort(arr))
print(np.sqrt(arr))
print(np.log(arr))
print(np.sin(arr))

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [49]:
#Broadcasting + vectorization together
#broadcasting handles shape & vectorization handles operation

arr=np.array([[1,2,3],
              [4,5,6]])

mean=np.array([2,3,4])

print(arr-mean)

[[-1 -1 -1]
 [ 2  2  2]]
